# Generated by Django 4.2.7 on 2023-12-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='Comm',
            field=models.IntegerField(null=True),
        ),
    ]
