# Generated by Django 4.2.7 on 2023-12-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bonus_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='salgrade',
            name='EmpName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='Comm',
            field=models.IntegerField(),
        ),
    ]
