# Generated by Django 4.2.7 on 2023-12-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_salgrade_empname_alter_bonus_comm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='EmpName',
        ),
        migrations.RemoveField(
            model_name='salgrade',
            name='EmpName',
        ),
        migrations.AddField(
            model_name='salgrade',
            name='Ename',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='Comm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Comm',
            field=models.IntegerField(),
        ),
    ]
