# Generated by Django 4.2.7 on 2023-12-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_bonus_empname_remove_salgrade_empname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salgrade',
            name='Ename',
        ),
    ]
