# Generated by Django 4.2.7 on 2023-12-11 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_salgrade_ename'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='EName',
            field=models.ForeignKey(default='Name', on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='salgrade',
            name='EName',
            field=models.ForeignKey(default='Name', on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
    ]
