# Generated by Django 4.2.7 on 2023-12-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bonus_ename_alter_salgrade_ename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='EName',
        ),
        migrations.RemoveField(
            model_name='salgrade',
            name='EName',
        ),
    ]
